### ISSUE TITLE
ImportError: cannot import name 'ForceReply' from 'telegram

### ISSUE THREAD

**Issue by Vysokostnyi** [sazonovanton/SirChatalot#1]
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    from telegram import ForceReply, Update, Bot
ImportError: cannot import name 'ForceReply' from 'telegram' (/home/runner/OldHummingPixel/venv/lib/python3.10/site-packages/telegram/__init__.py)


**Comment by sazonovanton** [comment]
You should use [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) with a version 20+.
