### ISSUE TITLE
Suggestions for improving the bot

### ISSUE THREAD

**Issue by MBudkin** [sazonovanton/SirChatalot#4]
Hello!
Thank you for your bot!

There are some suggestions for improving the bot:
- Make restrictions on the number of requests from each user, for example, by default, everyone can use up to 10 requests per day, and other users who are on a certain list - up to 100 times a day (or without restrictions).
- On request /count (for example), the user will be shown how many requests he made, for example: "Request counter: 4/10"
- It would be convenient if, when sending a request to the bot, the bot would respond like "Request in progress ...", and when the answer from ChatGPT would be ready, the last message from the bot would change to this answer. Or would send a new message with the answer. This would help to understand that the bot received the message, but it is being processed.

I tried to add these functions myself, but I don't know Python very well (mostly programmed with Arduino).
Thank you!

**Comment by sazonovanton** [comment]
1. Added rate limiter to restrict number of messages that can be processed from user in a time frame in a recent update.
2. /count is not implemented yet.
3. Progress message is good idea, I will try to add it later.

**Comment by sazonovanton** [comment]
2. I have added /limit command that should output user limit if it exists. Not really tested, but it should work.

**Comment by sazonovanton** [comment]
Now bot has ...typing status (for maximum 5 sec) while user waits for reply
