### ISSUE TITLE
Proposal to improve the limitation for using a bot as structuring voice messages.

### ISSUE THREAD

**Issue by MBudkin** [sazonovanton/SirChatalot#6]
At the moment "Max Session Length = 1" works like this:
1. We asked the bot a question
2. The bot responded according to the programmed pattern.
3. We asked another question.
4. The bot replied that our session was over and offered to try again.

Propose as follows:
1. Asked a question to the bot.
2. The bot answered and if this was the last attempt before clearing the chat - immediately warn the user that the chat has been cleared.

**What is it for?**
Since your bot supports voice messages, you can set up the bot model like this: SystemMessage = Highlight important points from the following message step by step.
Then the bot can be used like this:
- We were sent a big voice message in Telegram.
- We forward the voice message to the bot.
- The bot analyzes the voice message, gives out only important information in the chat and clears the context so that the next message is processed on a new one.

You can make and use a separate bot that will process voice messages and structure information.

Either do not use "Max Session Length", but immediately indicate somewhere that the history will not be saved. You can even separate it into a separate project, i.e. bot, purely for extracting only important information from voice messages or large texts.
It seems to me that it would be convenient not to listen to long voice messages :)

Or somewhere in the history public message code and then each message will be sent in a new way?

Thank you and good luck!

**Comment by sazonovanton** [comment]
I have added `MaxSessionLength` and `ChatDeletion` parameters to the [OpenAI] category in configuration file.
`MaxSessionLength` is a length of a session (only user messages count) with some action after approaching a limit.
Default action is creating summary and continue. You can set `ChatDeletion` value to `True` in config, so sesson on server side will be dropped if limit is reached. If both parameters are exist and enabled - user will see appendix to the message from the bot that informs that limit is close (if less than 3 messages left) and session is reset (on last message in session).

So now you do not need to uncomment code, just change config.

I will think about your case, maybe it is possible to change a bit of code to create a highlight mode, or just set session length for each mode separately.
